import java.io.IOException;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.ArrayList;

public class ConsultationDAO {

    public boolean addConsultation(Consultation consultation){

        String sql = "INSERT INTO Consultation " + 
             "(patient_id, doctor_id, consultation_date, consultation_time, diagnosis, notes, prescription_id) " +
             "VALUES (?, ?, ?, ?, ?, ?, ?)";


        //try-catch and try-with-resources
        //try-with-resources automatically frees/closes the resource after use is over
        try(Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){
                statement.setInt(1, consultation.getPatient().getPatientId());
                statement.setInt(2, consultation.getDoctor().getDoctorId());
                statement.setDate(3, java.sql.Date.valueOf(consultation.getDate()));    //differentiate from java.util.Date, otherewise import java.util.Date
                statement.setTime(4, java.sql.Time.valueOf(consultation.getTime()));
                statement.setString(5, consultation.getDiagnosis());
                statement.setString(6, consultation.getNotes());
                if(consultation.getPrescription() != null){
                    statement.setInt(7,consultation.getPrescription().getPrescriptionId());
                } else{
                    statement.setNull(7, java.sql.Types.INTEGER);
                }
                
                int rowsAffected = statement.executeUpdate(); 
                //sends commands to mySQL ie. execute the query
                //executeUpdate() is used for INSERT, UPDATE, DELETE and returns the number of rows affected.
                //executeQuery() is used for SELECT and returns a ResultSet.

                if(rowsAffected > 0){
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    //get the keys generated by AUTO INCREMENT as a ResultSet

                    if(generatedKeys.next()){
                        int generatedId = generatedKeys.getInt(1);
                        consultation.setConsultationId(generatedId);
                        return true;
                    }
                }

                return false;
        }
        catch(IOException e){
            System.out.println("Caught exception: "+ e.getMessage());
            return false;
        }
        catch(SQLException e){
            System.out.println("Caught excpetion: "+ e.getMessage());
            return false;
        }
    }

    public Consultation findConsultation(int consultation_id){
        /* 
        findConsultation(id) 
        → SQL SELECT using that ID 
        → retrieve the matching database row as ResultSet
        → construct and return a Consultation object.
        */
        String sql = "SELECT * FROM Consultation WHERE consultation_id = ?";


        try(Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql);){
                statement.setInt(1,consultation_id);

                ResultSet resultSet = statement.executeQuery();

                if(resultSet.next()){

                    PatientDAO patientDAO_obj = new PatientDAO();
                    DoctorDAO doctorDAO_obj = new DoctorDAO();
                    PrescriptionDAO prescriptionDAO_obj = new PrescriptionDAO();
                    
                    //NULL CHECK FOR PRESCRIPTION
                    int prescriptionId = resultSet.getInt("prescription_id");
                    
                    Prescription prescription = null;

                    if(!resultSet.wasNull()){
                        //wasNull() checks if the last column value retrieved was null
                        //Here the last value retrieved is prescription_id in the above statement
                        prescription = prescriptionDAO_obj.findPrescription(prescriptionId);
                    }

                    Consultation consultation = new Consultation(
                        resultSet.getInt("consultation_id"),
                        patientDAO_obj.findPatient(resultSet.getInt("patient_id")), 
                        doctorDAO_obj.findDoctor(resultSet.getInt("doctor_id")), 
                        resultSet.getDate("consultation_date").toLocalDate(), 
                        resultSet.getTime("consultation_time").toLocalTime(), 
                        resultSet.getString("diagnosis"), 
                        resultSet.getString("notes"), 
                        prescription
                    );

                    return consultation;
                }

        }
        catch(IOException e){
            System.out.println("Caught exception: " + e.getMessage());
            return null;
            //no consultation object so return null pointer
        }
        catch(SQLException e){
            System.out.println("Caught exception: " + e.getMessage());
            return null;
            //no consultation object so return null pointer
        }

        return null;
    }

    public boolean updateConsultation(Consultation consultation){
        String sql = "UPDATE consultation "+
                     "SET patient_id = ?, "+
                     "doctor_id = ?, "+
                     "consultation_date = ?, "+ 
                     "consultation_time = ?, "+
                     "diagnosis = ?, "+
                     "notes = ?, "+
                     "prescription_id = ? "+
                     "WHERE consultation_id = ?";

        try(Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql);
        ){
            //user will enter values in GUI and a consultation object will be created
            //Here we update the table using the values from that consultation object
            statement.setInt(1,consultation.getPatient().getPatientId());
            statement.setInt(2, consultation.getDoctor().getDoctorId());
            statement.setDate(3, java.sql.Date.valueOf(consultation.getDate()));
            //the mySQL date is different from the Java Date
            //Here in the Java model we have used LocalDate
            //But JDBC uses java.sql.Date
            //similarly below for Time
            statement.setTime(4, java.sql.Time.valueOf(consultation.getTime()));
            statement.setString(5, consultation.getDiagnosis());
            statement.setString(6, consultation.getNotes());
            if(consultation.getPrescription() != null){
                statement.setInt(7,consultation.getPrescription().getPrescriptionId());
            }
            else{
                statement.setNull(7,java.sql.Types.INTEGER);
            }
            statement.setInt(8,consultation.getConsultationId());

            int rowsAffected = statement.executeUpdate();
            if(rowsAffected > 0){
                return true;
            }
            return false;
        }
        catch(IOException e){
            System.out.println("Caught IOException: "+e.getMessage());
            return false;
        }
        catch(SQLException e){
            System.out.println("Caught SQLException: "+e.getMessage());
            return false;
        }
    }

    public boolean deleteConsultation(int consultationId){
        String sql = "DELETE FROM consultation " +
                     "WHERE consultation_id = ?";
        try(Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)){
                statement.setInt(1, consultationId);

                int rowsAffected = statement.executeUpdate();
                if(rowsAffected > 0){
                    return true;
                }

                return false;
        }
        catch(IOException e){
            System.out.println("Caught IOException: "+e.getMessage());
            return false;
        }
        catch(SQLException e){
            System.out.println("Cuahgt SQLException: "+e.getMessage());
            return false;
        }


    }

    public List<Consultation> getConsultationsByPatient(int patientId){

        PatientDAO patientDAO_obj = new PatientDAO();
        Patient patient = patientDAO_obj.findPatient(patientId);

        if(patient == null){
            System.out.println("Patient not found...");
            return null;
        }

        String sql = "SELECT * FROM consultation "+
                     "WHERE patient_id = ?";
        
        //create a PatientDAO object to use the findPatient() method
        //create a patient object to pass as paramater of Consultation() constructor

        try(Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)){
            
                List<Consultation> consultationsList = new ArrayList<Consultation>();
                //ArrayList is an implementation of the List interface
                
                statement.setInt(1,patientId);
                ResultSet resultSet = statement.executeQuery();

                //creating database access objects needed to find the Doctor and Prescription to be passed to the Consultation constructor
                DoctorDAO doctorDAO_obj = new DoctorDAO();
                PrescriptionDAO prescriptionDAO_obj = new PrescriptionDAO();

                while(resultSet.next()){
                    //need to retrieve all the necessary information for the Consultation constructor

                    Doctor doctor = doctorDAO_obj.findDoctor(resultSet.getInt("doctor_id"));
                    Prescription prescription = null;
                    int prescriptionId = resultSet.getInt("prescription_id");

                    if(!resultSet.wasNull()){
                        prescription = prescriptionDAO_obj.findPrescription(prescriptionId);
                    }

                    Consultation consultation = new Consultation(resultSet.getInt("consultation_id"), patient, doctor, resultSet.getDate("consultation_date").toLocalDate(), resultSet.getTime("consultation_time").toLocalTime(), resultSet.getString("diagnosis"), resultSet.getString("notes"), prescription);

                    consultationsList.add(consultation);
                }

                return consultationsList;
        }
        catch(IOException e){
            System.out.println("Caught IOException: "+e.getMessage());
            return null;
        }
        catch(SQLException e){
            System.out.println("Caught SQLException: "+e.getMessage());
            return null;
        }
    }

    public List<Consultation> getConsultationsByDoctor(int doctorId){

        String sql = "SELECT * FROM consultation "+
                     "WHERE doctor_id = ?";
        
        DoctorDAO doctorDAO_obj = new DoctorDAO();
        Doctor doctor = doctorDAO_obj.findDoctor(doctorId);
        //create a PatientDAO object to use the findPatient() method
        //create a patient object to pass as paramater of Consultation() constructor

        try(Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)){
            
                List<Consultation> consultationsList = new ArrayList<Consultation>();
                
                statement.setInt(1,doctorId);
                ResultSet resultSet = statement.executeQuery();

                //creating database access objects needed to find the Patient and Prescription to be passed to the Consultation constructor
                DoctorDAO doctorDAO_obj = new DoctorDAO();
                PrescriptionDAO prescriptionDAO_obj = new PrescriptionDAO();

                while(resultSet.next()){
                    //need to retrieve all the necessary information for the Consultation constructor

                    Doctor doctor = doctorDAO_obj.findDoctor(resultSet.getInt("doctor_id"));
                    Prescription prescription = null;

                    if(!resultSet.wasNull()){
                        prescription = prescriptionDAO_obj.findPrescription(resultSet.getInt("prescription_id"));
                    }

                    Consultation consultation = new Consultation(resultSet.getInt("consultation_id"), patient, doctor, resultSet.getDate("consultation_date").toLocalDate(), resultSet.getTime("consultation_time").toLocalTime(), resultSet.getString("diagnosis"), resultSet.getString("notes"), prescription);

                    consultationsList.add(consultation);
                }

                return consultationsList;
        }
        catch(IOException e){
            System.out.println("Caught IOException: "+e.getMessage());
            return null;
        }
        catch(SQLException e){
            System.out.println("Caught SQLException: "+e.getMessage());
            return null;
        }
    }

}